provinces = [
    # Sumatera
    'Nanggroe Aceh Darussalam',
    'Sumatera Utara',
    'Sumatera Barat',
    'Riau',
    'Kepulauan Riau',
    'Jambi',
    'Bengkulu',
    'Sumatera Selatan',
    'Kepulauan Bangka Belitung',
    'Lampung',
    'Aceh', # optional
    'Sumut', # optional
    'Sumbar', # optional
    'Kepri', # optional
    'Sumsel', # optional
    'Babel', # optional 

    # Jawa
    'Banten',
    'DKI Jakarta',
    'Jawa Barat',
    'Jawa Tengah',
    'Jawa Timur',
    'DI Yogyakarta',
    'Jabar', # optional
    'Jateng', # optional
    'Jatim', # optional
    'Jakarta', # optional
    'Yogyakarta', # optional
    'D.I.Y', # optional
    'D.I Yogyakarta', # optional

    # Kep. Nusa Tenggara
    'Bali',
    'Nusa Tenggara Barat',
    'Nusa Tenggara Timur',
    'NTB', # optional
    'NTT', # optional

    # Kalimantan
    'Kalimantan Barat',
    'Kalimantan Selatan',
    'Kalimantan Tengah',
    'Kalimantan Timur',
    'Kalimantan Utara',
    'Kalbar', # optional
    'Kalsel', # optional
    'Kalteng', # optional
    'Kaltim', # optional
    'Kaltara', # optional

    # Sulawesi
    'Gorontalo',
    'Sulawesi Barat',
    'Sulawesi Selatan',
    'Sulawesi Tenggara',
    'Sulawesi Tengah',
    'Sulawesi Utara',
    'Sulbar', # optional
    'Sulsel', # optional
    'Sulteng', # optional
    'Sultra', # optional
    'Sulut', # optional

    # Kep. Maluku
    'Maluku',
    'Maluku Utara',

    # Papua
    'Papua',
    'Papua Barat',
]


cities = [
    # Aceh
    'Aceh Barat',
    'Aceh Barat Daya',
    'Aceh Besar',
    'Aceh Jaya',
    'Aceh Selatan',
    'Aceh Singkil',
    'Aceh Tamiang',
    'Aceh Tengah',
    'Aceh Tenggara',
    'Aceh Timur',
    'Aceh Utara',
    'Bener Meriah',
    'Bireuen',
    'Gayo Lues',
    'Nagan Raya',
    'Pidie',
    'Pidie Jaya',
    'Simeulue',
    'Banda Aceh',
    'Langsa',
    'Lhokseumawe',
    'Sabang',
    'Subulussalam',

    # Bali
    'Badung',
    'Bangil',
    'Buleleng',
    'Gianyar',
    'Jembrana',
    'Karangasem',
    'Klungkung',
    'Tabanan',
    'Denpasar',

    # Banten
    'Lebak',
    'Pandeglang',
    'Serang',
    'Tangerang',
    'Cilegon',
    'Serang',
    'Tangerang',
    'Tangerang selatan',

    # Bengkulu
    'Bengkulu Selatan',
    'Bengkulu Tengah',
    'Bengkulu Utara',
    'Kaur',
    'kapahiang',
    'Lebong',
    'Mukomuko',
    'Rejang Lebong',
    'seluma',
    'Bengkulu',

    # D.I.Y
    'Bantul',
    'Gunung kildul', # optional
    'Gunungkidul'
    'Kulon Progo',
    'Sleman',
    'Yogyakarta',

    # D.K.I
    'Kepulauan Seribu',
    'Jakarta Barat',
    'Jakarta Pusat',
    'Jakarta Selatan',
    'Jakarta Timur',
    'Jakarta Utara',

    # Gorontalo
    ' Boalemo',
    ' Bone Bolango',
    ' Gorontalo',
    ' Gorontalo Utara',
    ' Pahuwato',
    ' Gorontalo',

    # Jambi
    'Batanghari',
    'Bungo',
    'Kerinci',
    'Merangin',
    'Muaro Jambi',
    'Sarolangun',
    'Tanjung Jabung Barat',
    'Tanjung Jabung Timur',
    'Tebo',
    'Jambi',
    'Sungai Penuh',

    # Jawa Barat
    'Bandung',
    'Bandung Barat',
    'Bekasi',
    'Bogor',
    'Ciamis',
    'Cianjur',
    'Cirebon',
    'Garut',
    'Indramayu',
    'Karawang',
    'Kuningan',
    'Majalengka',
    'Pangandaran',
    'Purwakarta',
    'Subang',
    'Sukabumi',
    'Sumedang',
    'Tasikmalaya',
    'Bandung',
    'Banjar',
    'Bekasi',
    'Bogor',
    'Cimahi',
    'Cirebon',
    'Depok',
    'Sukabumi',
    'Tasikmalaya',

    # Jawa Tengah
    'Banjarnegara',
    'Banyumas',
    'Batang',
    'Blora',
    'Boyolali',
    'Brebes',
    'Cilacap',
    'Demak',
    'Grobogan',
    'Jepara',
    'Karanganyar',
    'Kebumen',
    'Kendal',
    'Klaten',
    'Kudus',
    'Magelang',
    'Pati',
    'Pekalongan',
    'Pemalang',
    'Purbalingga',
    'Purworejo',
    'Rembang',
    'Semarang',
    'Sragen',
    'Sukoharjo',
    'Tegal',
    'Temanggung',
    'Wonogiri',
    'Wonosobo',
    'Magelang',
    'Pekalongan',
    'Salatiga',
    'Semarang',
    'Surakarta',
    'Tegal',

    # Jawa Timur
    'Bangkalan',
    'Banyuwangi',
    'Blitar',
    'Bojonegoro',
    'Bondowoso',
    'Gresik',
    'Jember',
    'Jombang',
    'Kediri',
    'Lamongan',
    'Lumajang',
    'Madiun',
    'Magetan',
    'Malang',
    'Mojokerto',
    'Nganjuk',
    'Ngawi',
    'Pacitan',
    'Pamekasan',
    'Pasuruan',
    'Ponorogo',
    'Probolinggo',
    'Sampang',
    'Sidoarjo',
    'Situbondo',
    'Sumenep',
    'Trenggalek',
    'Tuban',
    'Tulungagung',
    'Batu',
    'Blitar',
    'Kediri',
    'Madiun',
    'Malang',
    'Mojokerto',
    'Pasuruan',
    'Probolinggo',
    'Surabaya',

    # Kalimantan Barat
    'Bengkayang',
    'Kapuas Hulu',
    'Kayong Utara',
    'Ketapang',
    'Kubu Raya',
    'Landak',
    'Melawi',
    'Mempawah',
    'Sambas',
    'Sanggau',
    'Sekadau',
    'Sintang',
    'Pontianak',
    'Singkawang',

    # Kalimantan Selatan
    'Balangan',
    'Banjar',
    'Barito Kuala',
    'Hulu Sungai Selatan',
    'Hulu Sungai Tengah',
    'Hulu Sungai Utara',
    'Kotabaru',
    'Tabalong',
    'Tanah Bumbu',
    'Tanah Laut',
    'Tapin',
    'Banjarbaru',
    'Banjarmasin',

    # Kalimantan Tengah
    'Barito Selatan',
    'Barito Timur',
    'Barito Utara',
    'Gunung Mas',
    'Kapuas',
    'Katingan',
    'Kotawaringin Barat',
    'Kotawaringin Timur',
    'Lamandau',
    'Murung Raya',
    'Pulang Pisau',
    'Sukamara',
    'Seruyan',
    'Palangka Raya',
    'Palangkaraya' # optional

    # Kalimantan Timur
    'Berau',
    'Kutai Barat',
    'Kutai Kartanegara',
    'Kutai Timur',
    'Paser',
    'Penajam Paser Utara',
    'Mahakam Ulu',
    'Balikpapan',
    'Bontang',
    'Samarinda',

    # Kalimantan Utara
    'Bulungan',
    'Malinau',
    'Nunukan',
    'Tana Tidung',
    'Tarakan',

    # Kep. Bangka Belitung
    'Bangka',
    'Bangka Barat',
    'Bangka Selatan',
    'Bangka Tengah',
    'Belitung',
    'Belitung Timur',
    'Pangkal Pinang',
    'Pangkalpinang' # option
    
    # Kep. Riau
    'Bintan',
    'Karimun',
    'Kepulauan Anambas',
    'Lingga',
    'Natuna',
    'Batam',
    'Tanjung Pinang',
    'Tanjungpinang' # option

    # Lampung
    'Lampung Barat',
    'Lampung Selatan',
    'Lampung Tengah',
    'Lampung Timur',
    'Lampung Utara',
    'Mesuji',
    'Pesawaran',
    'Pringsewu',
    'Tanggamus',
    'Tulang Bawang',
    'Tulang Bawang Barat',
    'Way Kanan',
    'Pesisir Barat',
    'Bandar Lampung',
    'Metro',

    # Maluku
    'Buru',
    'Buru Selatan',
    'Kepulauan Aru',
    'Maluku Barat Daya',
    'Maluku Tengah',
    'Maluku Tenggara',
    'Maluku Tanimbar',
    'Seram Bagian Barat',
    'Seram Bagian Timur',
    'Ambon',
    'Tual',

    # Maluku Utara
    'Halmahera Barat',
    'Halmahera Tengah',
    'Halmahera Utara',
    'Halmahera Selatan',
    'Halmahera Timur',
    'Kepulauan Sula',
    'Pulau Morotai',
    'Pulau Taliabu',
    'Ternate',
    'Tidore Kepulauan',

    # NTB
    'Bima',
    'Dompu',
    'Lombok Barat',
    'Lombok Tengah',
    'Lombok Timur',
    'Lombok Utara',
    'Sumbawa',
    'Sumbawa Barat',
    'Bima',
    'Mataram',

    # NTT
    'Alor',
    'Belu',
    'Ende',
    'Flores Timur',
    'Kupang',
    'Lembata',
    'Malaka',
    'Manggarai',
    'Manggarai Barat',
    'Manggarai Timur',
    'Ngada',
    'Nagekeo',
    'Rote Ndao',
    'Sabu Raijua',
    'Sikka',
    'Sumba Barat',
    'Sumba Barat Daya',
    'Sumba Tengah',
    'Sumba Timur',
    'Timor Tengah Selatan',
    'Timor Tengah Utara',
    'Kupang',

    # Papua
    'Asmat',
    'Biak Numfor',
    'Boven Digoel',
    'Deiyai',
    'Dogiyai',
    'Intan Jaya',
    'Jayapura',
    'Jayawijaya',
    'Keerom',
    'Kepulauan Yapen',
    'Lanny Jaya',
    'Mamberamo Raya',
    'Mamberamo Tengah',
    'Mappi',
    'Merauke',
    'Mimika',
    'Nabire',
    'Nduga',
    'Paniai',
    'Pegunungan Bintang',
    'Puncak',
    'Puncak Jaya',
    'Sarmi',
    'Supiori',
    'Tolikara',
    'Waropen',
    'Yahukimo',
    'Yalimo',
    'Jayapura',

    # Papua barat
    'Fakfak',
    'Kaimana',
    'Manokwari',
    'Manokwari Selatan',
    'Maybrat',
    'Pegunungan Arfak',
    'Raja Ampat',
    'Sorong',
    'Sorong Selatan',
    'Tambrauw',
    'Teluk Bintuni',
    'Teluk Wondama',
    'Sorong',

    # Riau
    'Bengkalis',
    'Indragiri Hilir',
    'Indragiri Hulu',
    'Kampar',
    'Kepulauan Meranti',
    'Kuantan Singingi',
    'Pelalawan',
    'Rokan Hilir',
    'Rokan Hulu',
    'Siak',
    'Dumai',
    'Pekanbaru',

    # Sulawesi Barat
    'Majene',
    'Mamasa',
    'Mamuju',
    'Pasangkayu',
    'Polewali Mandar',
    'Mamuju Tengah',

    # Sulawesi Selatan
    'Bantaeng',
    'Barru',
    'Bone',
    'Bulukumba',
    'Enrekang',
    'Gowa',
    'Jeneponto',
    'Kepulauan Selayar',
    'Luwu',
    'Luwu Timur',
    'Luwu Utara',
    'Maros',
    'Pangkajene dan Kepulauan',
    'Pinrang',
    'Sidenreng Rappang',
    'Sinjai',
    'Soppeng',
    'Takalar',
    'Tana Toraja',
    'Toraja Utara',
    'Wajo',
    'Makassar',
    'Palopo',
    'Parepare',

    # Sulawesi Tengah
    'Banggai',
    'Banggai Kepulauan',
    'Banggai Laut',
    'Buol',
    'Donggala',
    'Morowali',
    'Parigi Moutong',
    'Poso',
    'Sigi',
    'Tojo Una-Una',
    'Tolitoli',
    'Palu',

    # Sulawesi Tenggara
    'Bombana',
    'Buton',
    'Buton Utara',
    'Buton Tengah',
    'Buton Selatan'
    'Kolaka',
    'Kolaka Timur',
    'Kolaka Utara',
    'Konawe',
    'Konawe Selatan',
    'Konawe Utara',
    'Konawe Kepulauan',
    'Muna',
    'Muna Barat'
    'Wakatobi',
    'Bau-Bau',
    'Kendari',

    # Sulawesi Utara
    'Bolaang Mongondow',
    'Bolaang Mongondow Selatan',
    'Bolaang Mongondow Timur',
    'Bolaang Mongondow Utara',
    'Kepulauan Sangihe',
    'Kepulauan Siau Tagulandang Biaro',
    'Kepulauan Talaud',
    'Minahasa',
    'Minahasa Selatan',
    'Minahasa Tenggara',
    'Minahasa Utara',
    'Bitung',
    'Kotamobagu',
    'Manado',
    'Tomohon',

    # Sumatera Barat
    'Agam',
    'Dharmasraya',
    'Kepulauan Mentawai',
    'Lima Puluh Kota',
    'Padang Pariaman',
    'Pasaman',
    'Pasaman Barat',
    'Pesisir Selatan',
    'Sijunjung',
    'Solok',
    'Solok Selatan',
    'Tanah Datar',
    'Bukittinggi',
    'Padang',
    'Padangpanjang',
    'Pariaman',
    'Payakumbuh',
    'Sawahlunto',
    'Solok',

    # Sumatera Selatan
    'Banyuasin',
    'Empat Lawang',
    'Lahat',
    'Muara Enim',
    'Musi Banyuasin',
    'Musi Rawas',
    'Musi Rawas Utara'
    'Ogan Ilir',
    'Ogan Komering Ilir',
    'Ogan Komering Ulu',
    'Ogan Komering Ulu Selatan',
    'Ogan Komering Ulu Timur',
    'Penukal Abab Lematang Ilir',
    'Lubuklinggau',
    'Pagar Alam',
    'Palembang',
    'Prabumulih',

    # Sumatera Utara
    'Asahan',
    'Batubara',
    'Batu Bara' # option
    'Dairi',
    'Deli Serdang',
    'Humbang Hasundutan',
    'Karo',
    'Labuhanbatu',
    'Labuhanbatu Selatan',
    'Labuhanbatu Utara',
    'Langkat',
    'Mandailing Natal',
    'Nias',
    'Nias Barat',
    'Nias Selatan',
    'Nias Utara',
    'Padang Lawas',
    'Padang Lawas Utara',
    'Pakpak Bharat',
    'Samosir',
    'Serdang Bedagai',
    'Simalungun',
    'Tapanuli Selatan',
    'Tapanuli Tengah',
    'Tapanuli Utara',
    'Toba Samosir',
    'Binjai',
    'Gunungsitoli',
    'Medan',
    'Padangsidempuan',
    'Pematangsiantar',
    'Sibolga',
    'Tanjungbalai',
    'Tebing Tinggi',
]

